version: '{branch}-{build}'

branches:
  only:
    - master
    - develop
    - actionlib

image: Visual Studio 2019

environment:
  nodejs_version: "10"
  PYTHON3: "c:\\Python37-x64"
  PYTHON2: "c:\\Python27"

clone_folder: c:\proj\rclnodejs

before_build:
  - cd c:\
  - md download
  - cd download
  - choco install -y wget cmake
  - "SET PATH=C:\\Program Files\\CMake\\bin;%PATH%"
  - appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2019-10-24/asio.1.12.1.nupkg
  - appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2019-10-24/cunit.2.1.3.nupkg
  - appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2019-10-24/eigen.3.3.4.nupkg
  - appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2019-10-24/tinyxml-usestl.2.6.2.nupkg
  - appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2019-10-24/tinyxml2.6.0.0.nupkg
  - appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2019-10-24/log4cxx.0.10.0.nupkg
  - choco install -y -s c:\download\ asio cunit eigen tinyxml-usestl tinyxml2 log4cxx
  - appveyor DownloadFile https://github.com/ros2/ros2/releases/download/release-dashing-20191018/ros2-dashing-20191018-windows-release-amd64.zip
  - 7z x -y "ros2-dashing-20191018-windows-release-amd64.zip" -o"c:\" > nul
  - setx -m OPENSSL_CONF C:\OpenSSL-Win64\bin\openssl.cfg
  - set PATH=C:\OpenSSL-Win64\bin;%PATH%
  - setx AMENT_PYTHON_EXECUTABLE "c:\Python37"
  - refreshenv
  - "SET PATH=%PYTHON3%;%PYTHON3%\\bin;%PYTHON3%\\Scripts;%PATH%"
  - python -m pip install -U catkin_pkg empy lark-parser lxml opencv-python pyparsing pyyaml setuptools colcon-common-extensions numpy

build_script:
  - cd  c:\proj\rclnodejs
  - git submodule init
  - git submodule update
  - ps: Install-Product node $env:nodejs_version x64
  - call c:\ros2-windows\local_setup.bat
  - "SET PATH=%PYTHON2%;%PYTHON2%\\bin;%PYTHON2%\\Scripts;%PATH%"
  - node --version
  - npm --version
  - python --version
  - npm install
  - npm run lint

test_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
  - "SET PATH=%PYTHON3%;%PYTHON3%\\bin;%PYTHON3%\\Scripts;C:\\Program Files\\CMake\\bin;%PATH%"
  - npm test
